//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Attempt
{
	public virtual object double a
	{
		get;
		set;
	}

	public virtual object double b
	{
		get;
		set;
	}

	public virtual object double c
	{
		get;
		set;
	}

	public virtual object double d
	{
		get;
		set;
	}

	public virtual object double e
	{
		get;
		set;
	}

	public virtual object double f
	{
		get;
		set;
	}

	public virtual object double g
	{
		get;
		set;
	}

	public virtual object double h
	{
		get;
		set;
	}

	public virtual object double i
	{
		get;
		set;
	}

	public virtual object double j
	{
		get;
		set;
	}

	public virtual object double MSE
	{
		get;
		set;
	}

}

